### PR TITLE
Bump Winston to fix webpack bundling

### LINKED ISSUE #61: Winston version 1.0.1 uses an outdated dependency pkginfo that appears to be incompatible with Webpack
The Node.js client library for SignalFx uses version 1.0.1 of Winston. Version 2.3.0 of the Winston library includes a fix for an issue related to an outdated pkginfo dependency (the pull request for Winston that resolved this issue is here: https://github.com/winstonjs/winston/pull/931). Versions of Winston prior to 2.3.0 are incompatible with any Node application bundled via Webpack, since pkginfo cannot find package.json from the bundled output.

Currently, using the Node.js client library for SignalFx in a Node application bundled via Webpack causes failure at the start script, `node dist/index`: 

Could not find package.json up from: /
    at Function../node_modules/pkginfo/lib/pkginfo.js.pkginfo.find 
    at Function../node_modules/pkginfo/lib/pkginfo.js.pkginfo.read 
    at ./node_modules/pkginfo/lib/pkginfo.js.module.exports 
    at Object.<anonymous> 
    at Object../node_modules/pkginfo/lib/pkginfo.js 
    at __webpack_require__ 
    at fn 
    at Object.<anonymous> 
    at Object../node_modules/winston/lib/winston.js 
    at __webpack_require__

### PR DESCRIPTION
**Pull request by the-realtom**
Fixes #61 

- Tested Webpack bundling now works after bumping the package

cc: @michelle-morin

### CODE REVIEW

**Comment by mmusik** [comment]
hi @the-realtom your PR is being looked at. It looks like besides the version bump we need to add some config to the logger, let me figure it out. This is the exemplary error I get in my tests when using your version `[winston] Attempt to write logs with no transports {"level":"error","message":"Failed to send datapoint: "}`

**Comment by mmusik** [comment]
@the-realtom I made additional config changes https://github.com/signalfx/signalfx-nodejs/pull/63 and I am waiting for the feedback.

**Comment by the-realtom** [comment]
> @the-realtom I made additional config changes #63 and I am waiting for the feedback.

thanks for doing that, I'll close this one 👍

**Comment by mmusik** [comment]
@the-realtom version 7.2.2 with upgraded winston is released. I haven't tested this with webpack specifically, so please let us know in case the problem is not solved.

**Pull request closed without merging**
